## TODO: OS Abstraction
  - name: "Install Apache2 on Ubuntu 16.04 LTS"
    apt:  
      name: apache2
      state: present
      update_cache: yes

  - name: "Enabling the mod_proxy apache module"
    command: a2enmod proxy
  
  - name: "Enabling the mod_proxy_http apache module"
    command: a2enmod proxy_http
    notify:
    - Restart Apache

    # removing this will make ansible cut off its own access to the server
  - name: "Enable TCP 22 - The only external port needed."
    ufw:
      port: "{{ firewall_port }}"
      rule: allow
      proto: tcp
      state: disabled

  # obscurity is not security and these services' loads will not compete
  # make sure to have DNS caching enabled for high volume environments
  # really high.  like backbone high  == in exchange for less human errors
  # by staff
  - name: "Enable TCP 80 - The only external port needed."
    ufw:
      port: "{{ firewall_port }}"
      rule: allow
      proto: tcp
      state: disabled
