## TODO: OS Abstraction
  - name: "Install Apache2 on Ubuntu 16.04 LTS"
    apt:  
      name: apache2
      state: present
      update_cache: yes

  - name: "Enabling the mod_proxy apache module"
    command: a2enmod proxy
  
  - name: "Enabling the mod_proxy_http apache module"
    command: a2enmod proxy_http
    notify:
    - Restart Apache

  - name: "Enable TCP 80 - The only external port needed."
    firewalld:
      port: 80/tcp
      permanent: true
      state: enabled

