  - name: "Restart ElasticSearch"
    systemd:
        name: "elasticsearch"
        enabled: yes
        masked: no
        state: stopped
        daemon_reload: yes

  - name: "Restart Apache"
    systemd:
      name: "apache2"
      enabled: yes
      masked: no
      state: restarted

