#  - name: "Reset the Kibana index"
#    uri:
#      url: "http://{{ ES_INSTANCE_DNS_NAME }}/.kibana"
#      method: DELETE
# Ansible URI module ignores below, and is problematic.  
# dropping to command.
#      ignore_errors: true


  - name: "Download/Extract the Kibana Tarball"
    unarchive:
      src: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kb.version }}-linux-x86_64.tar.gz"
      dest: "{{ kibana_base_path }}"
      remote_src: yes

  - name: "Fix Kibana Path"
    # thanks, ansible
    command: /bin/sh -c 'rm -Rf {{ kb.home_dir }}; sleep 1; mv -f {{ kibana_base_path }}/kibana-{{ kb.version }}* {{ kb.home_dir }}'

  - name: "Create group {{ kb.service_user }}"
    # This is a security need -- running as dedicated user and group to 
    # safegaurd against any arbitrary code execution or filesystem access 
    # exploits.  And also cats.
    group:
      name: "{{ kb.service_group }}"
      state: present

  - name: "Create user {{ kb.service_user }}"
    user:
      name: "{{ kb.service_user }}"
        # Important.  Prevents ability to log in remotely as the service 
        # account.  Password is also not set to further ensure that doesn't 
        # happen.  Existing accounts with proper sudoer permissions excepted.
      shell: "/bin/nologin"
      group: "{{ kb.service_group }}"

  - name: "Install kibana configuration"
    template: src=../templates/kibana.yml.jinja2 dest={{ kb.conf_dir }} force=yes 

    # set the permissions on the directory
  - name: "Set ownership of {{ kb.home_dir }} recursively to {{ kb.service_user }}:{{ kb.service_group }}"
    file: dest={{ kb.home_dir }} owner={{ kb.service_user }} group={{ kb.service_group }} recurse=yes

  - name: "Create the pid dir"
    file:
      path: "{{ kb.pid_dir }}"
      state: directory

  - name: "Delete the Kibana Index"
    # this is a hack because none of these services are actually api driven internally
    command: "curl -XDELETE \"{{ kb.elasticsearch_url }}/.kibana\" -H \"Content-Type: application/json\""
    ignore_errors: yes

  - name: "Set Default Index Pattern"
    command: "curl -XPOST \"{{ kb.elasticsearch_url }}/.kibana/doc/index-pattern:{{ fb.index_name }}\" -H \"Content-Type: application/json\" -d \"{  \"type\" : \"index-pattern\",  \"index-pattern\" : { \"title\": \"{{ FB_INDEX_NAME }}\", \"timeFieldName\": \"@timestamp\"  } }\""

  - name: "Create the log dir"
    file:
      path: "{{ kb.logs_dir }}"
      state: directory
      owner: "{{ kb.service_user }}"
      group: "{{ kb.service_group }}"
      
  - name: "Place systemd system unit target"
    # Need to do this outside of the systemd module so we can use a template
    template: src=../templates/kibana.service.jinja2 dest=/etc/systemd/system/kibana.service force=yes
  - name: "Enable systemd system unit target"
    systemd:
        name: "kibana"
        enabled: yes
        masked: no
        state: restarted
        daemon_reload: yes

  - name: "Install Reverse ProxyPass VirtualHost for Kibana"
    template: src=../templates/kibana_httpd.conf.jinja2 dest=/etc/apache2/sites-available/kibana.conf force=yes

  - name: "Enabling the ProxyPass for Kibana Apache VHost"
    command: a2ensite kibana

  # remove when done
  - name: "Reload/Restart the Apache Service"
    systemd:
      name: "apache2"
      enabled: yes
      masked: no
      state: restarted
