  - name: "Adding setfacl to Ubuntu to make it more intact as a distribution"
    apt: 
      name: acl
      state: present

  - name: "Add access rights for systemlogs to Filebeat user/group"
    acl: name={{ item }}  entity={{ fb_service_user }}  etype=user permissions="r" state=present
    with_items:
      fb.file_to_index

    # remove when done
  - name: "Reload/Restart the Filebeat Service"
    systemd:
      name: "filebeat"
      state: restarted
    
