  - name: "Download/Extract the Filebeat Tarball"
    unarchive:
      src: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ fb_version }}-linux-x86_64.tar.gz"
      dest: "{{ filebeat_base_path }}"
      remote_src: yes

  - name: "Fix Filebeat Path"
    # thanks, ansible
    command: /bin/sh -c 'rm -Rf {{ fb_home_dir }}; sleep 1; mv -f {{ filebeat_base_path }}/filebeat-{{ fb_version }}* {{ fb_home_dir }}'

  - name: "Create group {{ fb_service_group }}"
    # This is a security need -- running as dedicated user and group to 
    # safegaurd against any arbitrary code execution or filesystem access 
    # exploits.  And also cats.
    group:
      name: "{{ fb_service_group }}"
      state: present

  - name: "Create user {{ fb_service_user }}"
    user:
      name: "{{ fb_service_user }}"
        # Important.  Prevents ability to log in remotely as the service 
        # account.  Password is also not set to further ensure that doesn't 
        # happen.  Existing accounts with proper sudoer permissions excepted.
        # Logs can be accessed with facls if necessary to allow an approval process
        # after risk analysis.
      shell: "/bin/nologin"
      group: "{{ fb_service_group }}"

  - name: "Install filebeat configuration"
    template: src=../templates/filebeat/config.yml.jinja2 dest={{ fb_conf_dir }} force=yes 

    # set the permissions on the directory
  - name: "Set ownership of {{ fb_home_dir }} recursively to {{ fb_service_user }}:{{ fb_service_group }}"
    file: dest={{ fb_home_dir }} owner={{ fb_service_user }} group={{ fb_service_group }} recurse=yes

  - name: "Create the pid dir"
    file:
      path: "{{ fb_pid_dir }}"
      state: directory

  - name: "Place systemd system unit target"
    # Need to do this outside of the systemd module so we can use a template
    template: src=../templates/filebeat/systemd_unit.service.jinja2 dest=/etc/systemd/system/filebeat.service force=yes

  - name: "Enable systemd system unit target"
    systemd:
        name: "filebeat"
        enabled: yes
        masked: no
        state: restarted
        daemon_reload: yes
