## TODO: OS Abstraction
  - name: "Install Apache2 on Ubuntu 16.04 LTS"
    apt:  
      name: apache2
      state: present
      update_cache: yes

  - name: "Enabling the mod_proxy apache module"
    command: a2enmod proxy
  
  - name: "Enabling the mod_proxy_http apache module"
    command: a2enmod proxy_http

  - name: "Reload/Restart the Apache Service"
    systemd:
      name: "apache2"
      enabled: yes
      masked: no
      state: restarted
