  - name: "Restart ElasticSearch"
    systemd:
      name: "elasticsearch"
      state: restarted
      
  - name: "Restart Filebeat"
    systemd:
      name: "filebeat"
      state: restarted

  - name: "Restart Kibana"
    systemd:
      name: "kibana"
      state: restarted

  - name: "Sysctl HotFix for MAX_MAP_COUNT"
    # ubuntu-specific hotfix #1
    template: src=../templates/hotfixes/sysctl_elasticsearch.jinja2 dest=/etc/sysctl.d/elasticsearch.conf force=yes

  - name: "Weirder HotFix for MAX_MAP_COUNT -- REBOOT IN 10 SECONDS"
    # this part is due to a bug in sysctl in ubuntu 16.04 LTS that
    # causes it to look in the wrong place for some runtime configurable 
    # kernel parameters
    command: "/sbin/shutdown -h 10"
