---
- hosts: 
    - target_host
  remote_user: "root"
  vars:
    # All configuration items we should ever care about should be here.

    #################################################
    ## Elasticsearch Options
    ##
    ES_INSTANCE_NAME: "interpolation-buffet"
    ES_VERSION: "6.1.1"

    # the port that ES listens on
    ES_PORT: "9200"
    # the addr to bind to
    # use internal IP and proxypass from apache, it is safer, more 
    # stable, and more performant
    ES_BIND_HOST: "127.0.0.1"
    ES_INSTANCE_DNS_NAME: "elasticsearch.silogroup.org"

    # the url from which elasticsearch should be downloaded from
    ES_URL: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ ES_VERSION }}.tar.gz"

    # The user and group to run the elasticsearch process as
    ES_USR: "elasticsearch"
    ES_GRP: "elasticsearch"

    # systemd - where systemd wants elastiscearch to be
    ES_HOME: "{{ elasticsearch_base_path }}/elasticsearch-{{ ES_VERSION }}"

    # systemd - conf dir location
    ES_CONF: "{{ ES_HOME}}/config"

    # systemd - where the environment variables it needs set in its runtime go
    ES_ENV_FILE: "{{ ES_CONF }}/environment"

    # Elasticsearch data storage path
    ES_DATA: "{{ ES_HOME }}/data"
    ES_LOGS: "/var/log/elasticsearch/{{ ES_INSTANCE_NAME }}"
    ES_PID_PATH: "/var/run/elasticsearch"
    # Went with Oracle JRE because it sounded enterprisey compared to OpenJDK
    # Later moved to JDK because oracle jammed up the download URLs.

    # jvm options as needed
    ES_HEAP_INITIAL: "1g"
    ES_HEAP_MAX: "1g"

    #################################
    ## JAVA OPTIONS
    ##
    JDK_URL: "http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz"
    JDK_FILENAME: "jdk-8u151-linux-x64.tar.gz"
    JDK_PATH: "{{ ES_HOME }}/java"

    ####################
    ## KIBANA OPTIONS
    ##
    KB_PATH: "{{ kibana_base_path }}/kibana-{{ ES_VERSION }}"
    KB_CONF: "{{ KB_PATH }}/config/kibana.yml"
    KB_PORT: "5601"
    KB_HOST: "localhost"
    KB_INSTANCE_NAME: "{{ ES_INSTANCE_NAME }}"
    KB_ES_URL: "http://{{ ES_INSTANCE_DNS_NAME }}"
    KB_LOGS: "/var/log/kibana/{{ KB_INSTANCE_NAME }}"
    KB_USR: "kibana"
    KB_GRP: "kibana"
    KB_PID_PATH: "/var/run/kibana"
    KB_HOME: "{{ kibana_base_path }}/kibana-{{ ES_VERSION }}"
    KB_INSTANCE_DNS_NAME: "kibana.silogroup.org" 

    ###############################################
    ## Filebeat Options
    ##
    FB_PATH: "{{ filebeat_base_path }}/filebeat-{{ ES_VERSION }}"
    FB_INDEX_SYSLOG: "/var/log/syslog"
    FB_GRP: "filebeat"
    FB_USR: "filebeat"
    FB_HOME: "{{ filebeat_base_path }}/filebeat-{{ ES_VERSION }}"
    FB_PID_PATH: "/var/run/filebeat"  
    FB_CONF: "{{ FB_PATH }}/filebeat.yml"
    FB_INDEX_NAME: "almost-journald"
    FB_INSTANCE_DNS_NAME: "kibana.silogroup.org"
     
  tasks:
    - import_tasks: apache2.yml
    - import_tasks: elasticsearch.yml
    - import_tasks: java.yml
    - import_tasks: kibana.yml
    - import_tasks: filebeat.yml
    - import_tasks: filebeat_acls.yml
    - import_tasks: restart_services.yml
    
