    # remove when done
  - name: "Restart ElasticSearch"
    systemd:
      name: "elasticsearch"
      state: restarted
      
        # remove when done
  - name: "Restart Filebeat"
    systemd:
      name: "filebeat"
      state: restarted
      
        # remove when done
  - name: "Restart Kibana"
    systemd:
      name: "kibana"
      state: restarted

  - name: "Weirder HotFix for MAX_MAP_COUNT"
    # continuation of ubuntu-specific hotfix #1
    # this part is due to a bug in sysctl in ubuntu 16.04 LTS that
    # causes it to look in the wrong place for some runtime settable 
    # kernel parameters (seriously) 
    command: "reboot"
