  - name: "Download dedicated Java Runtime"
    # It is a dependency and the JRE available can't be assumed to be 
    # compatible or even present.  In addition to this, a 
    # distribution-independent solution here would not use the package 
    # manager due to package name disparity between distributions.  This is 
    # resolved by having an internal package repository for any runtime 
    # components used for all OS's in the environment, which is generally a 
    # good idea when OS continuity is not feasible in an environment.
    #
    # This Java task needs more abstraction.
    # Can't use get_url here or it'll fail.  Oracle requires magic that OpenJDK doesn't.
    shell: 'wget -P /tmp/ --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" {{ java_download_url }}'

  - name: "Extract Java Development Kit"
    unarchive: src=/tmp/{{ java_filename }} dest={{ es_home }} remote_src=yes

  - name: "Fix Java Path"
    # Thanks, ansible
    command: /bin/sh -c 'rm -Rf {{ java_home_dir }}; sleep 1; mv -f {{ es_home_dir }}/jdk* {{ java_home_dir }}'

  - name: "Set ownership of {{ java_home_dir }} recursively to {{ es_service_user }}:{{ es_service_group }}"
    file: dest={{ java_home_dir }} owner={{ es_service_user }} group={{ es_service_group }} recurse=yes
